name: consta_analytics_example
description: "Demonstrates how to use the consta_analytics plugin."

publish_to: 'none'

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  consta_analytics:
    # When depending on this package from a real application you should use:
    #   consta_analytics: ^x.y.z
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true