name: consta_analytics
description: "SPA SDK for Flutter"
version: 1.0.2
homepage: https://github.com/consta-design-system/consta-analytics-flutter-sdk.git

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  client_information: ^2.1.4
  uuid: ^4.4.2
  location: ^7.0.0
  hive: ^2.2.3
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.consta_analytics
        pluginClass: ConstaAnalyticsPlugin
      ios:
        pluginClass: ConstaAnalyticsPlugin